### ISSUE TITLE
Error parsing column 3

### ISSUE THREAD

**Issue by jbeck22** [docker-hotio/docker-readarr#14]
Just updated to the latest nightly build and I'm getting the below error. 

I'm running this as a docker on my Unraid server

**Error:**
Error parsing column 3 (Items=[ { "id": 0, "quality": 0, "items": [], "allowed": true }, { "id": 0, "quality": 1, "items": [], "allowed": true }, { "id": 0, "quality": 2, "items": [], "allowed": true }, { "id": 0, "quality": 3, "items": [], "allowed": true }, { "id": 0, "quality": 4, "items": [], "allowed": true }, { "id": 0, "quality": 5, "items": [], "allowed": true } ] - String)
Version 0.1.0.281

**Comment by hotio** [comment]
App issues should be reported to the app developer
