### ISSUE TITLE
Folder is not writable by user hotio

### ISSUE THREAD

**Issue by NowyQuei** [docker-hotio/docker-readarr#18]
error with file access...

docker-compose:
***************************
  readarr:
    image: hotio/readarr:nightly
    container_name: readarr
    restart: unless-stopped
    networks:
      - t2_proxy
    ports:
      - "$READARR_PORT:8787"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
    volumes:
      - $DOCKERDIR/readarr:/config
      - ${BOOKDIR}:/books
      - ${DOWNLOADDIR}:/downloads
      - /etc/localtime:/etc/localtime:ro
***************************

when i try to add a root folder (/books) to readarr this error will thrown:
Folder is not writable by user hotio

config files are written correctly

**Comment by hotio** [comment]
Fix your permissions

**Comment by NowyQuei** [comment]
they are correct dude!!!

**Comment by hotio** [comment]
Config files are written to /config not /books dude.

**Comment by NowyQuei** [comment]
when i try to use the config file folder the same will happen.
but i got you your are not interested to help here...
what a bad support

**Comment by hotio** [comment]
You just sad that config files were written ok....

**Comment by hotio** [comment]
And lets make one thing clear!!! This is not the place for support, let alone for a nightly Alpha Alpha app.
